### ISSUE TITLE
ignore @ mentions which are not meant for the bot itself

### ISSUE THREAD

**Issue by bb-Ricardo** [bb-Ricardo/icinga-slack-bot#44]
from #43 

We have the bot in a shared channel with all lot of people who probably muted this channel, and sometimes you want to @ a person and you will get the response I didn't understand the command I would love a ignore character if a line starts with @ or # the line is not ment for the bot this would save some responses of the bot during a short convo about the problem like # I have acked the problem working on it or @here, working on it

**Comment by william-sy** [comment]
Thanks for making this a ticket!

**Comment by william-sy** [comment]
Currently, I have it like this. But I am not too happy about it just yet. 
![Screenshot 2020-07-03 at 13 39 11](https://user-images.githubusercontent.com/17983840/86465871-c9361280-bd32-11ea-942b-5757923778fb.png)

The `@` always ignores if the `ignore_mentions` is `True` or `False` (ideally the command definition dictionary get adjusted accordingly?) 

But if you enable `ignore_mentions` then the mention function gets ignored and is send to the `@` command. I did not really see a different way of doing it. 

```
    # strip any mention "strings" from beginning of message, or ignore if desired.
    ignore=config["slack.ignore_mentions"]
    matches = re.search(mention_regex, slack_message)
    if matches and ignore == False:
        slack_message = matches.group(2).strip()
    elif matches and ignore == True:
        slack_message = "@"
```

```
  # This ideally gets ignored if ignore_menstions == False
  # Or should not be needed in the first place.
    {
        "name": "@",
        "shortcut": None,
        "short_description": "Please ignore me",
        "long_description": "This will ignore slack mentions to your team after the `@` mark.",
        "command_handler": "ignore_conversation"
    }
```
Perhaps you have a idea about it?

**Comment by bb-Ricardo** [comment]
added to 'next-release'. Can you test it?

**Comment by william-sy** [comment]
Hi, I tested this and it seems to work perfectly! 👍 

![Screenshot 2020-11-09 at 13 39 09](https://user-images.githubusercontent.com/17983840/98542500-536a2680-2291-11eb-97d3-523868a91117.png)


Sorry for the late response!

**Comment by bb-Ricardo** [comment]
no problem, thank you for testing. 👍
