### ISSUE TITLE
Unable to use Legacy Bot option in my space

### ISSUE THREAD

**Issue by pstryk** [bb-Ricardo/icinga-slack-bot#45]
Is there a way to use non-legacy api for bots in slack ? Unfortunately I don't see that option - I think legacy has been disabled for my wokspace.

**Comment by bb-Ricardo** [comment]
hi,

sorry for the late response. Did you use the link in the readme file?

Log in into Slack first and then use the link. it offers a Classic Bot.

**Comment by pstryk** [comment]
Yes I tried via the link in README.

I think the Legacy token has been removed per - https://api.slack.com/changelog/2020-02-legacy-test-token-creation-to-retire

**Comment by pstryk** [comment]
Please disregard. I think I found a way.

**Comment by bb-Ricardo** [comment]
Awesome, let me know what you think. Haven't got much feedback on this project so far.

**Comment by william-sy** [comment]
Hi, Thank you for this update I have looked at it And it seems to work perfectly :) (sorry for the late response)
![Screenshot 2020-11-09 at 13 39 09](https://user-images.githubusercontent.com/17983840/98542435-36355800-2291-11eb-9ad7-87ae95a6d9e6.png)
